### PR TITLE
Same config file name as release branch

### PR DESCRIPTION
**Pull request by loic35**
use the same name of _config_file for develop and release : openbaton-ase.properties
[Sorry for the wrong PR on master, my 1st one! on online github]

### CODE REVIEW

**Comment by mpauls** [comment]
very good for your first pull request. We will merge this change once we have aligned the bootstrap and debian packages to the new file name.

**Review by mpauls — APPROVED** [review]

**Comment by mpauls** [comment]
@flaviomu is this PR still needed or is it already solved and can be closed?

**Comment by flaviomu** [comment]
@mpauls I need to update the autoscaling configuration in the bootstrap files before merging it

**Comment by flaviomu** [comment]
@loic35 another PR merged your changes with some additional ones. 
Thank you for pointing out this issue.

**Pull request closed without merging**
